---
- name: Install Sendmail (Debian)
  apt: pkg=sendmail state=present
  when: ansible_os_family == "Ubuntu"
  become: true

- name: Install Sendmail (Debian)
  apt: pkg=sendmail state=present
  when: ansible_os_family == "Debian"
  become: true

- name: Install Sendmail (Red Hat)
  yum: pkg=sendmail state=present
  when: ansible_os_family == "RedHat"
  become: true
