---

- name: Install Sendmail (Debian)
  apt: pkg=sendmail state=installed
  when: ansible_os_family == "Debian"
  sudo: true

- name: Install Sendmail (Red Hat)
  yum: pkg=sendmail state=installed
  when: ansible_os_family == "RedHat"
  sudo: true
